WINDOW_TITLE = "Sinister Secrets"

# PLAYER
PLAYER_SPEED = 5
PLAYER_SPRINT_SPEED = 8
PLAYER_HEIGHT = 1.8
INTERACT_DISTANCE = 2.5
PLAYER_CROUCH_HEIGHT = 1.0
PLAYER_CROUCH_SPEED = 2.2
PLAYER_CROUCH_NOISE = 0.7
PLAYER_CAMERA_HEIGHT_RESPONSE = 12
STAMINA_MAX = 100
STAMINA_DRAIN_PER_SECOND = 22
STAMINA_REGEN_PER_SECOND = 15
STAMINA_REGEN_DELAY = 1.0
STAMINA_EXHAUSTED_RECOVERY = 25
NOISE_EVENT_LIFETIME = 1.5
WALK_NOISE_STRIDE = 1.5
SPRINT_NOISE_STRIDE = 2.0
CROUCH_NOISE_STRIDE = 1.5
HIDING_SAFE_SECONDS = 12
HIDING_NOISE_INTERVAL = 3
HIDING_NOISE_LEVEL = 4
HIDING_LOOK_YAW = 25
HIDING_LOOK_PITCH = 20
HIDING_REENTRY_DELAY = 1.0

# FLASHLIGHT
MAX_BATTERY = 100
FLASHLIGHT_START_BATTERY = 65
FLASHLIGHT_DRAIN_PER_SECOND = 3.5
LOW_BATTERY_THRESHOLD = 15

# LIGHTING (normalized RGB intensities; lights may exceed 1, distances in units)
HOUSE_AMBIENT_COLOR = (0.10, 0.11, 0.14)
HOUSE_FILL_COLOR = (0.015, 0.018, 0.025)
HOUSE_FOG_COLOR = (0.006, 0.008, 0.013)
HOUSE_FOG_DENSITY = 0.055
HOUSE_SIGN_COLOR = (32, 35, 41)  # Faint navigation labels; HUD stays unlit.
FLASHLIGHT_COLOR = (4.0, 3.78, 3.36)
FLASHLIGHT_FOV = 56
FLASHLIGHT_RANGE = 18
# Constant term limits close-up brightness; quadratic term softens distant light.
FLASHLIGHT_ATTENUATION = (3.2, 0.035, 0.025)
FLASHLIGHT_EXPONENT = 12
FLASHLIGHT_SHADOWS = True  # False is cheaper but permits light through walls.
FLASHLIGHT_SHADOW_RESOLUTION = 512

# GHOST
GHOST_PATROL_SPEED = 2.1
GHOST_INVESTIGATE_SPEED = 2.6
GHOST_CHASE_SPEED = 5.9  # Faster than walking, slower than an available sprint.
GHOST_VISION_DISTANCE = 12
GHOST_FOV = 85
GHOST_HEARING_BASE = 3
GHOST_CATCH_DISTANCE = 1.25
GHOST_LOST_SIGHT_SECONDS = 2.5
GHOST_SEARCH_SECONDS = 4.0
GHOST_ACTIVE_SEARCH_SECONDS = 14
GHOST_SEARCH_SPEED = 2.2
GHOST_DETECTION_SECONDS = 0.65
GHOST_DETECTION_DECAY = 1.2
GHOST_DARK_VISIBILITY = 0.65
GHOST_CROUCH_VISIBILITY = 0.6
GHOST_MEMORY_SECONDS = 12
GHOST_UNCERTAINTY_GROWTH = 0.6
GHOST_SEARCH_RADIUS = 5
GHOST_NOISE_COOLDOWN = 0.8
GHOST_SOUND_OCCLUSION = 0.55
GHOST_INSPECTION_SECONDS = 1.5

# ITEMS
EXIT_KEY_ID = "exit_key"

# HORROR PACING / ACCESSIBILITY (no menu yet; frequency 0 disables events)
HORROR_SEED = 1729
HORROR_EVENT_FREQUENCY = 1.0
HORROR_INTENSITY_LIMIT = 0.75
HORROR_INITIAL_QUIET_SECONDS = 30.0
HORROR_CHECK_SECONDS = 5.0
HORROR_COOLDOWN_SECONDS = (28.0, 48.0)
HORROR_POST_CHASE_QUIET_SECONDS = 18.0
HORROR_CATEGORY_WEIGHTS = {"lighting": 0.35, "environment": 0.40, "apparition": 0.25}
HORROR_REDUCED_FLICKER = True  # Slow, smooth dimming by default; no screen flashes.
JUMPSCARE_SECONDS = 1.8
JUMPSCARE_INTENSITY = 0.65  # 0 removes approach, shake, and darkening; catch still ends.
JUMPSCARE_REDUCED_SHAKE = False
JUMPSCARE_SHAKE_DEGREES = 0.45
