WINDOW_TITLE = "Sinister Secrets"

# PLAYER
PLAYER_SPEED = 5
PLAYER_SPRINT_SPEED = 8
PLAYER_HEIGHT = 1.8
INTERACT_DISTANCE = 2.5

# FLASHLIGHT
MAX_BATTERY = 100
FLASHLIGHT_START_BATTERY = 65
FLASHLIGHT_DRAIN_PER_SECOND = 3.5
LOW_BATTERY_THRESHOLD = 15

# GHOST
GHOST_PATROL_SPEED = 2.1
GHOST_INVESTIGATE_SPEED = 2.6
GHOST_CHASE_SPEED = 4.2
GHOST_VISION_DISTANCE = 12
GHOST_FOV = 85
GHOST_HEARING_BASE = 3
GHOST_CATCH_DISTANCE = 1.25
GHOST_LOST_SIGHT_SECONDS = 2.5
GHOST_SEARCH_SECONDS = 4.0

# ITEMS
EXIT_KEY_ID = "exit_key"
